\documentclass[aspectratio=169,12pt,t]{beamer}

\usepackage{graphicx}
\setbeameroption{hide notes}
\setbeamertemplate{note page}[plain]
\usepackage{listings}

\input{../LaTeX/header.tex}

% knitr options
<<options, echo=FALSE, results="hide",warning=FALSE,message=FALSE>>=
library(plotrix) # for draw.circle
library(RColorBrewer)
library(broman) # for colors
opts_chunk$set(echo=FALSE, results="hide", echo=FALSE,
               fig.path="MoreFigs/", verbose=TRUE,
               fig.height=6.5, fig.width=10,
               fig.align="center")

# background colors
bgcolor <- rgb(0.1, 0.1, 0.1, maxColorValue=1)
@

\title{Data visualization}
\author{\href{https://kbroman.org}{Karl Broman}}
\institute{Biostatistics \& Medical Informatics, UW{\textendash}Madison}
\date{\href{https://kbroman.org}{\tt \scriptsize \color{foreground} kbroman.org}
\\[-4pt]
\href{https://github.com/kbroman}{\tt \scriptsize \color{foreground} github.com/kbroman}
\\[-4pt]
\href{https://twitter.com/kwbroman}{\tt \scriptsize \color{foreground} @kwbroman}
\\[-4pt]
{\scriptsize Course web: \href{https://kbroman.org/AdvData}{\tt kbroman.org/AdvData}}
}


\begin{document}


{
\setbeamertemplate{footline}{} % no page number here
\frame{
  \titlepage

\note{
}
} }


\begin{frame}{Displaying data well}

\bbi
\item Be accurate and clear.

\item Let the data speak.

\bi
\item Show as much information as possible, taking care not to
  obscure the message.
\ei

\item Science not sales.

\bi
\item Avoid unnecessary frills (esp. gratuitous 3d).
\ei

\item In tables, every digit should be meaningful. Don't drop ending 0's.
\ei

\note{
}
\end{frame}




\begin{frame}[c]{Show the data}

\begin{columns}
\column{0.5\textwidth}

\figw{Figs/fig1a.png}{1.0}


\column{0.5\textwidth}

\only<1|handout 0>{\figw{Figs/fig1c.png}{1.0}}
\only<2|handout 0>{\figw{Figs/fig1d.png}{1.0}}
\only<3>{\figw{Figs/fig1e.png}{1.0}}
\only<4|handout 0>{\figw{Figs/fig1f.png}{1.0}}
\only<5|handout 0>{\figw{Figs/fig1g.png}{1.0}}
\only<6|handout 0>{\figw{Figs/fig1h.png}{1.0}}


\end{columns}

\note{

}

\end{frame}




\begin{frame}[c]{Avoid pie charts}


\begin{columns}
\column{0.5\textwidth}

\figw{Figs/fig2a_rev.png}{1.0}


\column{0.5\textwidth}

\only<1|handout 0>{\figw{Figs/fig2c.png}{1.0}}
\only<2|handout 0>{\figw{Figs/fig2d.png}{1.0}}
\only<3>{\figw{Figs/fig2e.png}{1.0}}

\end{columns}

\note{

}
\end{frame}





\begin{frame}{Avoid pie charts}

\only<1|handout 0>{\figh{Figs/piecharts.pdf}{0.81}}
\only<2|handout 0>{\figh{Figs/piecharts_3d.pdf}{0.81}}
\only<3>{\figh{Figs/piecharts_3d_w_bars.pdf}{0.81}}
\only<4|handout 0>{\figh{Figs/piecharts_w_bars.pdf}{0.81}}

\bigskip

\hfill \lolit \footnotesize
via \href{https://twitter.com/MonaChalabi/status/527121946073632768/photo/1}{\tt @MonaChalabi}
(\href{https://bit.ly/pie_vs_barchart}{\tt bit.ly/pie\_vs\_barchart})

\note{
}
\end{frame}




\end{document}




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage

\headsize \color{yellow}
\hfill \begin{minipage}{5.75in}
\centering
Consider logs
\end{minipage}

\vspace{30mm}

\begin{minipage}[t]{4.5in}
\vspace*{0cm}

\includegraphics[width=4.5in]{Figs/fig3a.png}
\end{minipage}
\hspace{25mm}
\begin{minipage}[t]{4.5in}
\vspace*{0cm}

\includegraphics[width=4.5in]{Figs/fig3b.png}
\end{minipage}


\newpage

\addtocounter{page}{-1}

\headsize \color{yellow}
\hfill \begin{minipage}{5.75in}
\centering
Consider logs
\end{minipage}

\vspace{30mm}

\begin{minipage}[t]{4.5in}
\vspace*{0cm}

\includegraphics[width=4.5in]{Figs/fig3a.png}
\end{minipage}
\hspace{25mm}
\begin{minipage}[t]{4.5in}
\vspace*{0cm}

\includegraphics[width=4.5in]{Figs/fig3c.png}
\end{minipage}


\newpage

\addtocounter{page}{-1}

\headsize \color{yellow}
\hfill \begin{minipage}{5.75in}
\centering
Consider logs
\end{minipage}

\vspace{30mm}

\begin{minipage}[t]{4.5in}
\vspace*{0cm}

\includegraphics[width=4.5in]{Figs/fig3a.png}
\end{minipage}
\hspace{25mm}
\begin{minipage}[t]{4.5in}
\vspace*{0cm}

\includegraphics[width=4.5in]{Figs/fig3d.png}
\end{minipage}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\newpage


\headsize \color{yellow}
\hfill \begin{minipage}{5.75in}
\centering
Consider logs
\end{minipage}

\vspace{30mm}

\centerline{\includegraphics[height=6in]{Figs/fig5c.png}}


\newpage

\addtocounter{page}{-1}

\headsize \color{yellow}
\hfill \begin{minipage}{5.75in}
\centering
Consider logs
\end{minipage}

\vspace{30mm}

\centerline{\includegraphics[height=6in]{Figs/fig5d.png}}

\newpage

\addtocounter{page}{-1}

\headsize \color{yellow}
\hfill \begin{minipage}{5.75in}
\centering
Consider logs
\end{minipage}

\vspace{30mm}

\centerline{\includegraphics[height=6in]{Figs/fig5e.png}}

\newpage

\addtocounter{page}{-1}

\headsize \color{yellow}
\hfill \begin{minipage}{5.75in}
\centering
Consider logs
\end{minipage}

\vspace{30mm}

\centerline{\includegraphics[height=6in]{Figs/fig5f.png}}

\newpage

\addtocounter{page}{-1}

\headsize \color{yellow}
\hfill \begin{minipage}{5.75in}
\centering
Consider logs
\end{minipage}

\vspace{30mm}

\centerline{\includegraphics[height=6in]{Figs/fig5b.png}}

\newpage


\headsize \color{yellow}
\hfill \begin{minipage}{5.75in}
\centering
Take differences
\end{minipage}

\vspace{30mm}

\centerline{\includegraphics[height=6in]{Figs/fig5a.png}}



\newpage
\thispagestyle{empty}

\headsize \color{yellow}
\hfill \begin{minipage}{6.75in}
\centering
Another ``take logs'' example
\end{minipage}

\vspace{30mm}

\centerline{\includegraphics[height=5in]{MoreFigs/broman_fig1.jpg}}

\vfill \hfill \smallestsize \color{blue}
Broman et al., Am J Hum Genet 63:861-869, 1998, Fig. 1



\newpage


\headsize \color{yellow}
\hfill
\begin{minipage}{6.25in}
\centering
Ease comparisons

\bigskip

\color{blue} \smallersize
(things to be compared should be adjacent)
\end{minipage}

\vspace{10mm}

<<genotype_and_sex, fig.height=5.5>>=
par(mfrow=c(1,2))
set.seed(11341)
me <- c(10, 15, 17, 12, 16, 18)
se <- runif(length(me), 0.5, 1)
me <- me[c(1,4,2,5,3,6)]
lo <- me - se
hi <- me + se
xd <- 0.2
xat <- c(1, 2, 3)
xat <- sort(c(xat - xd, xat + xd))
par(bg=bgcolor, fg="white", col="white", las=1, col.axis="white",
    col.lab="white")
plot(0, 0, type="n", xlab="", xaxt="n", ylab="Phenotype",
     ylim=range(c(lo, hi))+c(-1, +1), xlim=range(xat)+c(-xd, xd)*2,
     xaxs="i", yaxs="i")
abline(h=pretty(c(lo, hi)), col="gray25")
segments(xat, lo, xat, hi, lwd=2)
segments(xat-xd/8, lo, xat+xd/8, lo, lwd=2)
segments(xat-xd/8, hi, xat+xd/8, hi, lwd=2)
segments(xat-xd/4, me, xat+xd/4, me, lwd=2)
axis(side=1, at=xat, rep(c("Female", "Male"), 3), cex.axis=0.7,
     fg="white", col.axis="white")
axis(side=1, at=1:3, c("AA", "AB", "BB"), col.axis="white",
     tick=FALSE, line=2, cex.axis=1.3)


me <- me[c(1,3,5,2,4,6)]
se <- se[c(1,3,5,2,4,6)]
lo <- me - se
hi <- me + se
xd <- 0.2
xat <- c(0.3, 0.6, 0.9, 1.5, 1.8, 2.1)
plot(0, 0, type="n", xlab="", xaxt="n", ylab="Phenotype",
     ylim=range(c(lo, hi))+c(-1, +1), xlim=range(xat)+c(-xd, xd)*2,
     xaxs="i", yaxs="i")
abline(h=pretty(c(lo, hi)), col="gray25")
segments(xat, lo, xat, hi, lwd=2)
segments(xat-xd/8, lo, xat+xd/8, lo, lwd=2)
segments(xat-xd/8, hi, xat+xd/8, hi, lwd=2)
segments(xat-xd/4, me, xat+xd/4, me, lwd=2)
axis(side=1, at=xat, rep(c("AA", "AB", "BB"), 2),
     fg="white", col.axis="white")
axis(side=1, at=c(0.6, 1.8), c("Female", "Male"), col.axis="white",
     tick=FALSE, line=2, cex.axis=1.3)
@








\newpage


\headsize \color{yellow}
\hfill
\begin{minipage}{6.25in}
\centering
Ease comparisons

\bigskip

\color{blue} \smallersize
(add a bit of color)
\end{minipage}

\vspace{10mm}

<<genotype_and_sex_color, fig.height=5.5>>=
par(mfrow=c(1,2))
set.seed(11341)
me <- c(10, 15, 17, 12, 16, 18)
se <- runif(length(me), 0.5, 1)
me <- me[c(1,4,2,5,3,6)]
lo <- me - se
hi <- me + se
xd <- 0.2
xat <- c(1, 2, 3)
xat <- sort(c(xat - xd, xat + xd))
pink <- brocolors("crayons")["Tickle Me Pink"]
blue <- brocolors("crayons")["Cerulean"]
col <- rep(c(pink, blue), 3)
par(bg=bgcolor, fg="white", col="white", col.axis="white", col.lab="white",
    las=1)
plot(0, 0, type="n", xlab="", xaxt="n", ylab="Phenotype",
     ylim=range(c(lo, hi))+c(-1, +1), xlim=range(xat)+c(-xd, xd)*2,
     xaxs="i", yaxs="i")
abline(h=pretty(c(lo, hi)), col="gray25")
segments(xat, lo, xat, hi, lwd=2, col=col)
segments(xat-xd/8, lo, xat+xd/8, lo, lwd=2, col=col)
segments(xat-xd/8, hi, xat+xd/8, hi, lwd=2, col=col)
segments(xat-xd/4, me, xat+xd/4, me, lwd=2, col=col)
axis(side=1, at=xat, rep("", 6), cex.axis=0.7)
for(i in seq(along=xat))
  axis(side=1, at=xat[i], rep(c("Female", "Male"), 3)[i], cex.axis=0.7,
       col="white", col.axis=col[i], tick=FALSE)
axis(side=1, at=1:3, c("AA", "AB", "BB"),
     tick=FALSE, line=2, cex.axis=1.3)


me <- me[c(1,3,5,2,4,6)]
se <- se[c(1,3,5,2,4,6)]
lo <- me - se
hi <- me + se
xd <- 0.2
xat <- c(0.3, 0.6, 0.9, 1.5, 1.8, 2.1)
col <- rep(c(pink, blue), rep(3, 2))
plot(0, 0, type="n", xlab="", xaxt="n", ylab="Phenotype",
     ylim=range(c(lo, hi))+c(-1, +1), xlim=range(xat)+c(-xd, xd)*2,
     xaxs="i", yaxs="i")
abline(h=pretty(c(lo, hi)), col="gray25")
segments(xat, lo, xat, hi, lwd=2, col=col)
segments(xat-xd/8, lo, xat+xd/8, lo, lwd=2, col=col)
segments(xat-xd/8, hi, xat+xd/8, hi, lwd=2, col=col)
segments(xat-xd/4, me, xat+xd/4, me, lwd=2, col=col)
axis(side=1, at=xat, rep(c("AA", "AB", "BB"), 2),
     col="white", col.axis="white")
for(i in 1:2)
  axis(side=1, at=c(0.6, 1.8)[i], c("Female", "Male")[i], col.axis=col[c(1,4)][i],
       tick=FALSE, line=2, cex.axis=1.3)
@



\newpage


\headsize \color{yellow}
\hfill
\begin{minipage}{6.75in}
\centering
Which comparison is easiest?
\end{minipage}

\vfill

<<many_plots, >>=
par(mfrow=c(2,3), bg=bgcolor, col="white", fg="white",
    col.axis="white", col.lab="white", las=1,
    mar=c(4.1, 4.1, 1.1, 1.1))
ht <- c(83, 114, 36, 67, 114, 154, 137)
names(ht) <- rep("", length(ht))
names(ht)[4:5] <- c("A", "B")
col <- rep(bgcolor, length(ht))
col[4:5] <- c(pink, blue)

barplot(ht, col=col, border="white", ylim=c(0, max(ht)*1.1))
u <- par("usr")
rect(u[1], u[3], u[2], u[4], border="white")


o <- c(4, 2, 3, 1, 5, 6, 7)
barplot(ht[o], col=col[o], border="white", ylim=c(0, max(ht)*1.1))
u <- par("usr")
rect(u[1], u[3], u[2], u[4], border="white")

htlist <- list(ht[o][1:4], ht[o][5:7])
collist <- list(col[o][1:4], col[o][5:7])
lablist <- list(names(ht)[o][1:4], names(ht)[o][5:7])
plot(0, 0, type="n", xaxt="n", xlab="", ylab="", xlim=c(0.5, 2.5),
     ylim=c(0, max(sapply(htlist, sum))*1.1), yaxs="i", xaxs="i")
xl <- c(0.75, 1.65)
xr <- c(1.35, 2.25)
for(i in 1:2) {
  top <- cumsum(htlist[[i]])
  bot <- cumsum(c(0, htlist[[i]]))
  for(j in seq(along=htlist[[i]])) {
    rect(xl[i], bot[j], xr[i], top[j], border="white",
         col=collist[[i]][j])
    text((xl[i] + xr[i])/2, (bot[j]+top[j])/2, lablist[[i]][j], col=bgcolor)
  }
}

htlist[[2]] <- rev(htlist[[2]])
collist[[2]] <- rev(collist[[2]])
lablist[[2]] <- rev(lablist[[2]])
plot(0, 0, type="n", xaxt="n", xlab="", ylab="", xlim=c(0.5, 2.5),
     ylim=c(0, max(sapply(htlist, sum))*1.1), yaxs="i", xaxs="i")
xl <- c(0.75, 1.65)
xr <- c(1.35, 2.25)
for(i in 1:2) {
  top <- cumsum(htlist[[i]])
  bot <- cumsum(c(0, htlist[[i]]))
  for(j in seq(along=htlist[[i]])) {
    rect(xl[i], bot[j], xr[i], top[j], border="white",
         col=collist[[i]][j])
    text((xl[i] + xr[i])/2, (bot[j]+top[j])/2, lablist[[i]][j], col=bgcolor)
  }
}

collist[[1]][2] <- collist[[2]][3]
collist[[2]][3] <- collist[[2]][2]
lablist[[1]][2] <- lablist[[2]][3]
lablist[[2]][3] <- lablist[[2]][2]
plot(0, 0, type="n", xaxt="n", xlab="", ylab="", xlim=c(0.5, 2.5),
     ylim=c(0, max(sapply(htlist, sum))*1.1), yaxs="i", xaxs="i")
xl <- c(0.75, 1.65)
xr <- c(1.35, 2.25)
for(i in 1:2) {
  top <- cumsum(htlist[[i]])
  bot <- cumsum(c(0, htlist[[i]]))
  for(j in seq(along=htlist[[i]])) {
    rect(xl[i], bot[j], xr[i], top[j], border="white",
         col=collist[[i]][j])
    text((xl[i] + xr[i])/2, (bot[j]+top[j])/2, lablist[[i]][j], col=bgcolor)
  }
}

o <- c(1,2,3,5,6,4,7)
pie(ht[o], col=col[o], border="white")
@



\newpage


\headsize \color{yellow}
\hfill
\begin{minipage}{6.25in}
\centering
Don't distort the quantities

\color{blue} \smallsize
(value $\propto$ {\color{pink} radius})
\end{minipage}

\vfill

<<circles_messed_up>>=
gL <- c("Arabidopsis"=0.145, "Human" = 3.2, "Wheat"=17)

library(broman)
green <- brocolors("crayons")["Caribbean Green"]

mult <- sqrt(gL["Human"]/pi)/gL["Human"]
par(mar=rep(0.1, 4), bg=bgcolor, col="white")
plot(0,0,type="n", xlim=c(0, 25), ylim=c(0, 25), xlab="", ylab="",
     xaxt="n", yaxt="n", xaxs="i", yaxs="i")
draw.circle(20, 20, gL["Wheat"],     nv=251, lwd=2, border="wheat", col="wheat")
text(5/mult, 4/mult, "Wheat (17 Gbp)", col=bgcolor, cex=1.5)
draw.circle( 1,  1,  gL["Arabidopsis"], nv=251, lwd=2, border=green, col=green)
text(1.3, 0.5, "Arabidopsis (0.145 Gbp)", col=green, adj=c(0, 0.5))
draw.circle( 4,  6,  gL["Human"],   nv=251, lwd=2, border=pink, col=pink)
text(4, 4, "Human (3.2 Gbp)", col=bgcolor, adj=c(0.5, 0.5))
@

\newpage


\headsize \color{yellow}
\hfill
\begin{minipage}{6.25in}
\centering
Don't distort the quantities

\color{blue} \smallsize
(value $\propto$ area)
\end{minipage}

\vfill

<<circles_fixed>>=
mx <- 25*mult
par(mar=rep(0.1, 4), bg=bgcolor, col="white")
plot(0,0,type="n", xlim=c(0, mx), ylim=c(0, mx), xlab="", ylab="",
     xaxt="n", yaxt="n", xaxs="i", yaxs="i")
draw.circle(5, 4, sqrt(gL["Wheat"]/pi),     nv=251, lwd=2, border="wheat", col="wheat")
text(5, 4, "Wheat (17 Gbp)", col=bgcolor, cex=1.5)
draw.circle(mult*0.9, mult*1.7, sqrt(gL["Arabidopsis"]/pi), nv=251, lwd=2, border=green, col=green)
text(1.3*mult, 0.5*mult, "Arabidopsis (0.145 Gbp)", col=green, adj=c(0, 0.5))
draw.circle(4*mult,  6*mult,  sqrt(gL["Human"]/pi),   nv=251, lwd=2, border=pink, col=pink)
text(4*mult, 4*mult, "Human (3.2 Gbp)", col=bgcolor, adj=c(0.5, 0.5))
@


\newpage


\headsize \color{yellow}
\hfill
\begin{minipage}{6.25in}
\centering
Don't use areas at all

\color{blue} \smallsize
(value $\propto$ length)
\end{minipage}

\vfill

<<circles_barplot,fig.width=6.5>>=
par(mar=c(3.1, 5.1, 0.6, 0.6), bg=bgcolor, las=1, fg="white",
    col.lab="white", col.axis="white")
b <- barplot(gL, col=c(green, pink, "wheat"), ylab="Genome size (Gbp)",
             ylim=c(0, 18), col.lab="white", yaxs="i", border=c(green, pink, "wheat"),
             names.arg=rep("", 3), cex.lab=1.5, cex.axis=1.5)
u <- par("usr")
rect(u[1], u[3], u[2], u[4], border="white")
axis(side=1, at=b, names(gL), col.axis="white", col="white",
     cex.axis=1.5, tick=FALSE)
@



\newpage


\headsize \color{yellow}
\hfill
\begin{minipage}{5.75in}
\centering
Encoding data
\end{minipage}

\vspace{30mm}

\smallersize \color{white}
\hspace{1in} \begin{minipage}[t]{4in}
\vspace*{0mm}

{\smallsize \color{pink} Quantities}
\vspace{5mm}

\begin{itemize}
\item Position
\item Length
\item Angle
\item Area
\item Luminance {\color{blue} (light/dark)}
\item Chroma {\color{blue} (amount of color)}
\end{itemize}

\end{minipage}
\hfill
\begin{minipage}[t]{4in}
\vspace*{0mm}

{\smallsize \color{pink} Categories}
\vspace{5mm}

\begin{itemize}
\item Shape
\item Hue {\color{blue} (which color)}
\item Texture
\item Width
\end{itemize}

\end{minipage}

\newpage


\headsize \color{yellow}
\hfill
\begin{minipage}{6.25in}
\centering
Ease comparisons

\bigskip

\color{blue} \smallersize
(align things vertically)
\end{minipage}

\vfill

<<histograms>>=
par(mfrow=c(2,2), bg=bgcolor, fg="white", col="white",
    col.axis="white", col.lab="white")
set.seed(85588489)
fem <- rnorm(600, 64, 2.8)
mal <- rnorm(600, 68, 2.8)
jt <- c(fem, mal)
br <- seq(min(jt), max(jt), len=51)
hist(fem, breaks=br, yaxt="n", ylab="", main="Women",
     xlab="Height (in)", col.main=pink)
hist(mal, breaks=br, yaxt="n", ylab="", main="Men",
     xlab="Height (in)", col.main=blue)
hist(mal, breaks=br, yaxt="n", ylab="", main="Men",
     xlab="Height (in)", col.main=blue)
@


\newpage


\headsize \color{yellow}
\hfill
\begin{minipage}{6.25in}
\centering
Ease comparisons

\bigskip

\color{blue} \smallersize
(use common axes)
\end{minipage}

\vfill

<<histograms2>>=
par(mfcol=c(2,2), bg=bgcolor, fg="white", col="white",
    col.axis="white", col.lab="white")
hist(fem, breaks=51, yaxt="n", ylab="", main="Women",
     xlab="Height (in)", col.main=pink)
hist(mal, breaks=51, yaxt="n", ylab="", main="Men",
     xlab="Height (in)", col.main=blue)
hist(fem, breaks=br, yaxt="n", ylab="", main="Women",
     xlab="Height (in)", col.main=pink)
hist(mal, breaks=br, yaxt="n", ylab="", main="Men",
     xlab="Height (in)", col.main=blue)
@


\newpage


\headsize \color{yellow}
\hfill
\begin{minipage}{6.25in}
\centering
Use labels not legends
\end{minipage}

\vfill

<<direct_label>>=
data(iris)
par(bg=bgcolor, fg="white", col.lab="white", las=1, col.axis="white")
par(mfrow=c(1, 2))
green <- rgb(102,254,102,maxColorValue=255)
yellow <- rgb(255, 255, 102, maxColorValue=255)
purple <- rgb(203,102,254,maxColorValue=255)
jitx <- runif(nrow(iris), -0.1, 0.1)
jity <- runif(nrow(iris), -0.02, 0.02)
plot(I(Petal.Width + jity) ~ I(Petal.Length + jitx), data=iris,
     bg=c(blue, green, pink)[as.numeric(Species)],
     xlab = "Petal length (cm)", ylab="Petal width (cm)", pch=21)
legend("topleft", levels(iris$Species), pt.bg=c(blue, green, pink),
       pch=21, col="white")

plot(I(Petal.Width + jity) ~ I(Petal.Length + jitx), data=iris,
     bg=c(blue, green, pink)[as.numeric(Species)], col="white",
     xlab = "Petal length (cm)", ylab="Petal width (cm)", pch=21)
text(2.2,  0.4,  levels(iris$Species)[1], adj=c(0, 0.5), col=blue)
text(3.25, 1.4,  levels(iris$Species)[2], adj=c(1, 0.5), col=green)
text(4.7,  2.2,  levels(iris$Species)[3], adj=c(1, 0.5), col=pink)
@






\newpage


\headsize \color{yellow}
\hfill
\begin{minipage}{6.25in}
\centering
Don't sort alphabetically
\end{minipage}

\vfill

<<alphabet>>=
load("Data/health.RData")

par(mfrow=c(1,2), bg=bgcolor, las=1, fg="white",
    col.lab="white", col.axis="white",
    mar=c(5.1, 10.1, 1.1, 1.1))

plot(0, 0, type="n", xlab="Health care spending (% GDP)",
     ylab="", yaxt="n", xlim=c(0, max(health[,2])*1.05), xaxs="i",
     ylim=c(nrow(health), 0)+0.5, yaxs="i")
axis(side=2, at=1:25, health[,1])
abline(v=seq(5, 15, by=5), col="gray25")
abline(h=seq(1, 25, by=5), col=blue)
points(health[,2], 1:25, pch=16)
axis(side=2, at=seq(1, 25, by=5), rep("", 5), col.ticks=blue)

o <- order(health[,2], decreasing=TRUE)
plot(0, 0, type="n", xlab="Health care spending (% GDP)",
     ylab="", yaxt="n", xlim=c(0, max(health[,2])*1.05), xaxs="i",
     ylim=c(nrow(health), 0)+0.5, yaxs="i")
axis(side=2, at=1:25, health[o,1])
abline(v=seq(5, 15, by=5), col="gray25")
abline(h=seq(1, 25, by=5), col=blue)
points(health[o,2], 1:25, pch=16)
axis(side=2, at=seq(1, 25, by=5), rep("", 5), col.ticks=blue)
@






\newpage


\headsize \color{yellow}
\hfill
\begin{minipage}{6.25in}
\centering
Must you include 0?
\end{minipage}

\vfill

<<include_0>>=
par(mfrow=c(1,2), bg=bgcolor, las=1, fg="white",
    col.lab="white", col.axis="white")
rate <- c(96.5, 98.1, 99.2)
b <- barplot(rate, col=c(blue, green, pink), ylab="Detection rate (%)",
             ylim=c(0, 120), col.lab="white", yaxs="i",
             border=c(blue, green, pink), xlab="Method",
             names.arg=rep("", 3), cex.lab=1.5, cex.axis=1.5)
u <- par("usr")
rect(u[1], u[3], u[2], u[4], border="white")
axis(side=1, at=b, LETTERS[1:3], col.axis="white", col="white",
     cex.axis=1.5, tick=FALSE)
text(b, rate+5, paste0(rate, "%"))

plot(0, 0, type="n", ylim=c(95, 100), yaxs="i",
     xlim=c(0.5, 3.5), xaxt="n", xlab="Method",
     cex.lab=1.5, cex.axis=1.5, ylab="Detection rate (%)")
abline(h=96:99, col="gray25")
x <- 1:3
xd <- 0.2
se <- sqrt(rate*(100-rate)/1000)
segments(x, rate-se, x, rate+se, lwd=2, col=c(blue, green, pink))
segments(x-xd/2, rate-se, x+xd/2, rate-se, lwd=2, col=c(blue, green, pink))
segments(x-xd/2, rate+se, x+xd/2, rate+se, lwd=2, col=c(blue, green, pink))
segments(x-xd, rate, x+xd, rate, lwd=3, col=c(blue, green, pink))
axis(side=1, at=1:3, LETTERS[1:3], cex.axis=1.5)
@






\newpage

\headsize \color{yellow}
\hfill \begin{minipage}{5.75in}
\centering
A bad table
\end{minipage}

\vspace{30mm}

\centerline{\includegraphics[width=8in]{Figs/tableB.png}}


\newpage

\headsize \color{yellow}
\hfill \begin{minipage}{5.75in}
\centering
Fewer digits
\end{minipage}

\vspace{30mm}

\centerline{\includegraphics[width=8in]{Figs/tableA.png}}


\newpage

\headsize \color{yellow}
\hfill \begin{minipage}{5.75in}
\centering
Yuck!
\end{minipage}

\vspace{10mm}

\centerline{\includegraphics[height=6in]{Figs/lancet_table.pdf}}

\vfill \hfill \smallestsize \color{blue}
Feigen et al., Lancet 383:245-255, 2014, Table 1

\vspace{5mm}

\newpage

\addtocounter{page}{-1}

\headsize \color{yellow}
\hfill \begin{minipage}{5.75in}
\centering
Yuck!
\end{minipage}

\vspace{10mm}

\centerline{\includegraphics[height=6in]{Figs/lancet_table_crop.png}}

\vfill \hfill \smallestsize \color{blue}
Feigen et al., Lancet 383:245-255, 2014, Table 1

\vspace{5mm}

\newpage

\headsize \color{yellow}
\hfill \begin{minipage}{5.75in}
\centering
What was wrong with that?
\end{minipage}

\vspace{30mm}

\smallersize \color{white}

\hspace{0.5in} \begin{minipage}[t]{9in}
\begin{itemize}

\itemsep18pt

\item {\color{pink} Way} too many digits.

\item Numbers aren't aligned.

\item Numbers to be compared aren't anywhere near each other.

\item The interesting comparisons are horizontal rather than
  vertical.

\item It would be much better as a multi-panel figure.
\end{itemize} \end{minipage}

\newpage

\headsize \color{yellow}
\hfill
\begin{minipage}{5.75in}
\centering
One last example
\end{minipage}

\vspace{0mm}

\begin{center}
\begin{minipage}[t]{2.5in}

  \vspace*{0mm}

\centerline{\includegraphics[height=6.2in]{Crashes/Figs/chalabi-dearmona-distracted.png}}

\end{minipage}
\hspace{5mm}
\begin{minipage}[t]{2.5in}

  \vspace*{0mm}

\centerline{\includegraphics[height=6.2in]{Crashes/Figs/chalabi-dearmona-speeding.png}}

\end{minipage}
\hspace{5mm}
\begin{minipage}[t]{2.5in}

\vspace*{0mm}

\centerline{\includegraphics[height=6.2in]{Crashes/Figs/chalabi-dearmona-drinking.png}}


\end{minipage}
\end{center}


\hfill \smallestsize \color{blue}
\href{https://fivethirtyeight.com/datalab/which-state-has-the-worst-drivers/}{\tt fivethirtyeight.com/datalab/which-state-has-the-worst-drivers}

\newpage

\headsize \color{yellow}
\hfill
\begin{minipage}{5.75in}
\centering
An alternative
\end{minipage}

\vspace{10mm}

\centerline{\href{https://www.biostat.wisc.edu/~kbroman/D3/car_crashes/}{\includegraphics{Crashes/crashes.pdf}}}


\newpage

\headsize \color{yellow}
\hfill
\begin{minipage}{5.75in}
\centering
Scatterplots
\end{minipage}

\vspace{10mm}

\centerline{\href{https://www.biostat.wisc.edu/~kbroman/D3/car_crashes/}{\includegraphics{Crashes/crashes_scatter.pdf}}}




\newpage



\headsize \color{yellow}
\hfill
\begin{minipage}{5.75in}
\centering
Summary I
\end{minipage}

\vspace{30mm}

\smallersize \color{white}
\hspace{0.5in} \begin{minipage}{9.5in}

\begin{itemize}
\itemsep18pt

\item Show the data

\item Avoid chart junk

\item Consider taking logs and/or differences

\item Put the things to be compared next to each other

\item Use color to set things apart, but consider color blind folks

\item Use position rather than angle or area to represent quantities

\end{itemize}

\end{minipage}



\newpage

\headsize \color{yellow}
\hfill
\begin{minipage}{5.75in}
\centering
Summary II
\end{minipage}

\vspace{30mm}

\smallersize \color{white}
\hspace{0.5in} \begin{minipage}{9.5in}

\begin{itemize}
\itemsep18pt


\item Align things vertically to ease comparisons

\item Use common axis limits to ease comparisons

\item Use labels rather than legends

\item Sort on meaningful variables (not alphabetically)

\item Must 0 be included in the axis limits?

\item Use scatterplots to explore relationships

\end{itemize}

\end{minipage}


\newpage





\headsize \color{yellow}
\hfill
\begin{minipage}{5.75in}
\centering
Inspirations
\end{minipage}

\vspace{30mm}

\smallersize \color{white}
\hspace{0.5in} \begin{minipage}{9.5in}

\begin{itemize}
\item Hadley Wickham
{\smallestsize \color{blue}
(slides at \href{http://courses.had.co.nz}{\tt http://courses.had.co.nz})}

\item Naomi Robbins
{\smallestsize \color{blue}
(\emph{Creating more effective graphs})}

\item Howard Wainer

\item Andrew Gelman

\item Dan Carr

\item Edward Tufte

\end{itemize}

\end{minipage}




\newpage


\headsize \color{yellow}
\hfill \begin{minipage}{5.75in}
\centering
Further reading
\end{minipage}

\vspace{30mm}
\smallestsize \color{white}

\hspace{0.5in} \begin{minipage}[t]{9in}
\begin{itemize}

\itemsep12pt

\item ER Tufte (1983) The visual display of quantitative information.
Graphics Press.
\item ER Tufte (1990) Envisioning information. Graphics Press.
\item ER Tufte (1997) Visual explanations. Graphics Press.

\vspace*{8mm}

\item A Gelman, C Pasarica, R Dodhia (2002) Let's practice what we preach:
Turning tables into graphs. The American Statistician 56:121-130

\vspace*{8mm}

\item NB Robbins (2004) Creating more effective graphs. Wiley

\vspace*{8mm}

\item Nature Methods columns: \href{https://bit.ly/points_of_view}{\tt bit.ly/points\_of\_view}

\vspace*{8mm}

\item These slides: \href{https://bit.ly/graphs2018}{\tt bit.ly/graphs2018}

\end{itemize}
\end{minipage}



\end{document}
